### ISSUE TITLE
Fell over while installing Rookie core

### ISSUE THREAD

**Issue by IanMayo** [abukwaik/rookie#1]
Just tried to install Rookie theme:
- Copied unzipped folder to themes folder via FTP
- Activated theme
- Theme indicated that rookie-core need to be installed

Process fell over with this warning:
`Fatal error: Class 'TGM_Bulk_Installer' not found in /homepages/13/d565924428/htdocs/clickandbuilds/DeepBlueC5839/wp-content/themes/rookie/admin/class-tgm-plugin-activation.php on line 1577`

**Comment by abukwaik** [comment]
Hi Ian,
This error usually caused when you "bulk plugins install" due to some server configurations. That's strange because the theme only required 1 plugin. I think your download file is gone bad or maybe some files corrupted after upload? I've tested the theme on 3 different servers: local server, free shared host and VPS .. never had this error before.
Try to Install and activate the plugin manually or re-download the theme and install it through Dashboard.

**Comment by IanMayo** [comment]
sure, will do.

**Comment by abukwaik** [comment]
OK, please let me know.

**Comment by IanMayo** [comment]
Sure - repeated process and it worked fine. Let's call it "user error" :-)

**Comment by abukwaik** [comment]
You're welcome :)
